// <auto-generated />
using EFInstituto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace TPabm.Migrations
{
    [DbContext(typeof(EFInstitutoContext))]
    [Migration("20220626045342_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFInstituto.Alumno", b =>
                {
                    b.Property<int>("AlumnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlumnoApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlumnoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.HasKey("AlumnoId");

                    b.HasIndex("MateriaId");

                    b.ToTable("Alumno");
                });

            modelBuilder.Entity("EFInstituto.Carrera", b =>
                {
                    b.Property<int>("CarreraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarreraModalidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarreraNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarreraId");

                    b.ToTable("Carrera");
                });

            modelBuilder.Entity("EFInstituto.Maestro", b =>
                {
                    b.Property<int>("MaestroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MaestroApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaestroNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.HasKey("MaestroId");

                    b.HasIndex("MateriaId")
                        .IsUnique();

                    b.ToTable("Maestro");
                });

            modelBuilder.Entity("EFInstituto.Materia", b =>
                {
                    b.Property<int>("MateriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<string>("MateriaDivision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MateriaNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MateriaId");

                    b.HasIndex("CarreraId");

                    b.ToTable("Materia");
                });

            modelBuilder.Entity("EFInstituto.Alumno", b =>
                {
                    b.HasOne("EFInstituto.Materia", "Materia")
                        .WithMany("Alumnos")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("EFInstituto.Maestro", b =>
                {
                    b.HasOne("EFInstituto.Materia", "Materia")
                        .WithOne("Maestro")
                        .HasForeignKey("EFInstituto.Maestro", "MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("EFInstituto.Materia", b =>
                {
                    b.HasOne("EFInstituto.Carrera", "Carrera")
                        .WithMany("Materias")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("EFInstituto.Carrera", b =>
                {
                    b.Navigation("Materias");
                });

            modelBuilder.Entity("EFInstituto.Materia", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("Maestro");
                });
#pragma warning restore 612, 618
        }
    }
}
